PROGRAM TEST_RAIN_ICE


IMPLICIT NONE

INTEGER   :: KPROMA  
INTEGER   :: KKA  
INTEGER   :: KKU  
INTEGER   :: KKL  
INTEGER   :: KLON    
INTEGER   :: KLEV     
INTEGER   :: KFDIA
INTEGER   :: KRR      
INTEGER   :: KDUM
INTEGER   :: KTCOUNT  
INTEGER   :: KSPLITR  
INTEGER   :: KEZDIAG  

INTEGER :: IFILE

INTEGER :: IPROMA, ISIZE

CHARACTER(LEN=128) :: CLFILE, CLDIR
INTEGER :: MYPROC, IPROC, ICOUNT
INTEGER, PARAMETER :: NPROC = 1248
INTEGER :: ICOUNTTOT (NPROC), ISIZETOT (NPROC)

ICOUNT = 0

ICOUNTTOT = 0
ISIZETOT = 0

CLDIR = '/scratch/work/riette/inout_rain_ice_big_3D'

DO 

READ (*, *) CLFILE
IF (TRIM (CLFILE) == 'STOP') EXIT

ICOUNT = ICOUNT + 1

IF (MODULO (ICOUNT, 100) == 0) PRINT *, ICOUNT

READ (CLFILE (1:4), *) MYPROC

IFILE = 77
OPEN (IFILE, FILE=TRIM (CLDIR)//'/'//TRIM (CLFILE), FORM='UNFORMATTED') 
READ (IFILE) IPROMA, ISIZE
READ (IFILE) KLON, KDUM, KLEV, KRR
CLOSE (IFILE)

ICOUNTTOT (MYPROC) = ICOUNTTOT (MYPROC) + KLON * KLEV
ISIZETOT (MYPROC) = ISIZETOT (MYPROC) + ISIZE

IF (MODULO (ICOUNT, 10000) == 0) THEN
  WRITE (CLFILE, '("count",I10.10,".txt")') ICOUNT
  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='FORMATTED')
  DO IPROC = 1, NPROC
    WRITE (IFILE, '(I8,I8,I8)') IPROC, ISIZETOT (IPROC), ICOUNTTOT (IPROC)
  ENDDO
  CLOSE (IFILE)
ENDIF

ENDDO

OPEN (IFILE, FILE='count.txt', FORM='FORMATTED')
DO IPROC = 1, NPROC
  WRITE (IFILE, '(I8,I8,I8)') IPROC, ISIZETOT (IPROC), ICOUNTTOT (IPROC)
ENDDO
CLOSE (IFILE)


END PROGRAM
