PROGRAM TEST_RAIN_ICE

USE MODD_CONF
USE MODD_CST, ONLY: CST
USE MODD_RAIN_ICE_DESCR, ONLY: RAIN_ICE_DESCR
USE MODD_RAIN_ICE_PARAM, ONLY: RAIN_ICE_PARAM
USE MODD_PARAM_ICE,      ONLY: PARAM_ICE
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t

USE MODD_BUDGET, ONLY: TBUDGETDATA, NBUDGET_RH, TBUCONF
USE MODI_BUDGET_DDH
USE MODE_FILL_DIMPHYEX, ONLY: FILL_DIMPHYEX

USE MODI_RAIN_ICE

USE MODI_RAIN_ICE_OLD

USE DDH_MIX , ONLY : TYP_DDH
USE YOMLDDH , ONLY : TLDDH
USE YOMMDDH , ONLY : TMDDH

IMPLICIT NONE

INTEGER   :: KPROMA  
INTEGER   :: KKA  
INTEGER   :: KKU  
INTEGER   :: KKL  
INTEGER   :: KLON    
INTEGER   :: KLEV     
INTEGER   :: KRR      
INTEGER   :: KDUM

CHARACTER (LEN=4)   :: CSUBG_AUCV_RC
CHARACTER (LEN=80)  :: CSUBG_AUCV_RI
LOGICAL             :: OSEDIC 
CHARACTER (LEN=4)   :: CSEDIM  
CHARACTER (LEN=4)   :: CMICRO  
REAL                :: PTSTEP 


REAL,    ALLOCATABLE, DIMENSION(:,:,:) :: PRS   
REAL,    ALLOCATABLE, DIMENSION(:,:,:) :: PFPR 
REAL,    ALLOCATABLE, DIMENSION(:,:,:) :: PRT   
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PDZZ     
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PRHODJ  
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PRHODREF
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PEXNREF 
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PPABSM  
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PHLC_HRC
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PHLC_HCF
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PHLI_HRI
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PHLI_HCF
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PTHT    
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PSIGS   
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PCLDFR  
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PTHS    
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PEVAP 
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: PCIT  
REAL,    ALLOCATABLE, DIMENSION(:)     :: PSEA  
REAL,    ALLOCATABLE, DIMENSION(:)     :: PTOWN  
REAL,    ALLOCATABLE, DIMENSION(:)     :: PINPRR
REAL,    ALLOCATABLE, DIMENSION(:)     :: PINPRS
REAL,    ALLOCATABLE, DIMENSION(:)     :: PINPRG
REAL,    ALLOCATABLE, DIMENSION(:)     :: ZINDEP     
REAL,    ALLOCATABLE, DIMENSION(:,:)   :: ZRAINFR
REAL,    ALLOCATABLE, DIMENSION(:)     :: ZINPRC    
LOGICAL, ALLOCATABLE, DIMENSION(:,:) :: LLMICRO 

LOGICAL :: OWARM 
LOGICAL :: OCND2 

INTEGER :: IFILE


TYPE(TBUDGETDATA), DIMENSION(NBUDGET_RH) :: YLBUDGET 
TYPE(DIMPHYEX_t) :: YLDIMPHYEX

INTEGER :: IPROMA, ISIZE

CHARACTER(LEN=128) :: CLFILE



CMICRO='ICE3'

CALL GETARG (1, CLFILE)

PTSTEP = 25.0000000000000
KRR = 6
OSEDIC = .TRUE.
OCND2 = .FALSE.
CSEDIM = 'STAT'
CSUBG_AUCV_RC = 'PDF'
CSUBG_AUCV_RI = 'NONE'
OWARM = .TRUE.

IFILE = 77
OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
READ (IFILE) IPROMA, ISIZE
READ (IFILE) KLON, KDUM, KLEV, KRR

PRINT *, KLON, KDUM, KLEV, KRR

ALLOCATE (PRT      (KLON,KLEV,KRR))
ALLOCATE (PRS      (KLON,KLEV,KRR))
ALLOCATE (PFPR     (KLON,KLEV,KRR))
ALLOCATE (PDZZ     (KLON,KLEV))
ALLOCATE (PRHODJ   (KLON,KLEV))
ALLOCATE (PRHODREF (KLON,KLEV))
ALLOCATE (PEXNREF  (KLON,KLEV))
ALLOCATE (PPABSM   (KLON,KLEV))
ALLOCATE (PHLC_HRC (KLON,KLEV))
ALLOCATE (PHLC_HCF (KLON,KLEV))
ALLOCATE (PHLI_HRI (KLON,KLEV))
ALLOCATE (PHLI_HCF (KLON,KLEV))
ALLOCATE (PTHT     (KLON,KLEV))
ALLOCATE (PSIGS    (KLON,KLEV))
ALLOCATE (PCLDFR   (KLON,KLEV))
ALLOCATE (PTHS     (KLON,KLEV))
ALLOCATE (PEVAP    (KLON,KLEV))
ALLOCATE (PCIT     (KLON,KLEV))
ALLOCATE (PSEA     (KLON))
ALLOCATE (PTOWN    (KLON))
ALLOCATE (PINPRR   (KLON))
ALLOCATE (PINPRS   (KLON))
ALLOCATE (PINPRG   (KLON))
ALLOCATE (LLMICRO  (KLON,KLEV))
ALLOCATE (ZINDEP   (KLON))
ALLOCATE (ZRAINFR  (KLON,KLEV))
ALLOCATE (ZINPRC   (KLON))

READ (IFILE) LLMICRO
READ (IFILE) PEXNREF
READ (IFILE) PDZZ
READ (IFILE) PRHODJ
READ (IFILE) PRHODREF
READ (IFILE) PEXNREF
READ (IFILE) PPABSM
READ (IFILE) PCIT
READ (IFILE) PCLDFR
READ (IFILE) PHLC_HRC
READ (IFILE) PHLC_HCF
READ (IFILE) PHLI_HRI
READ (IFILE) PHLI_HCF
READ (IFILE) PTHT
READ (IFILE) PRT
READ (IFILE) PTHS
READ (IFILE) PRS
READ (IFILE) PSIGS
READ (IFILE) PSEA
READ (IFILE) PTOWN
READ (IFILE) PCIT
READ (IFILE) PRS
READ (IFILE) ZINPRC
READ (IFILE) PINPRR
READ (IFILE) PEVAP
READ (IFILE) PINPRS
READ (IFILE) PINPRG
READ (IFILE) ZINDEP
READ (IFILE) ZRAINFR
READ (IFILE) PFPR
CLOSE (IFILE)

CALL FILL_DIMPHYEX(YLDIMPHYEX, KLON, 1, KLEV, 0, KLON)

CALL RAIN_ICE(  YLDIMPHYEX, CST, PARAM_ICE, RAIN_ICE_PARAM, &
             &  RAIN_ICE_DESCR, TBUCONF, &
             &  IPROMA, ISIZE, &
             &  OSEDIC=OSEDIC, OCND2=OCND2, HSEDIM=CSEDIM, &
             &  HSUBG_AUCV_RC=CSUBG_AUCV_RC, HSUBG_AUCV_RI=CSUBG_AUCV_RI,&
             &  OWARM=OWARM, &
             &  PTSTEP=2*PTSTEP, &
             &  KRR=KRR, ODMICRO=LLMICRO, PEXN=PEXNREF,            &
             &  PDZZ=PDZZ, PRHODJ=PRHODJ, PRHODREF=PRHODREF,PEXNREF=PEXNREF,&
             &  PPABST=PPABSM, PCIT=PCIT, PCLDFR=PCLDFR,  &
             &  PHLC_HRC=PHLC_HRC, PHLC_HCF=PHLC_HCF, &
             &  PHLI_HRI=PHLI_HRI, PHLI_HCF=PHLI_HCF, &
             &  PTHT=PTHT,PRVT=PRT(1,1,1),PRCT=PRT(1,1,2), &
             &  PRRT=PRT(1,1,3), &
             &  PRIT=PRT(1,1,4), PRST=PRT(1,1,5), &
             &  PRGT=PRT(1,1,6),       &
             &  PTHS=PTHS, PRVS=PRS(1,1,1),PRCS=PRS(1,1,2),&
             &  PRRS=PRS(1,1,3),&
             &  PRIS=PRS(1,1,4),PRSS= PRS(1,1,5),PRGS= PRS(1,1,6),&
             &  PINPRC=ZINPRC,PINPRR=PINPRR,PEVAP3D=PEVAP,&
             &  PINPRS=PINPRS, PINPRG=PINPRG, PINDEP=ZINDEP, PRAINFR=ZRAINFR, &
             &  PSIGS=PSIGS, &
             &  TBUDGETS=YLBUDGET, KBUDGETS=SIZE(YLBUDGET), &
             &  PSEA=PSEA, PTOWN=PTOWN, PFPR=PFPR)



END PROGRAM
