PROGRAM TEST_RAIN_ICE

USE MODD_CONF
USE MODD_CST, ONLY: CST
USE MODD_RAIN_ICE_DESCR, ONLY: RAIN_ICE_DESCR
USE MODD_RAIN_ICE_PARAM, ONLY: RAIN_ICE_PARAM
USE MODD_PARAM_ICE,      ONLY: PARAM_ICE
USE MODD_DIMPHYEX,   ONLY: DIMPHYEX_t

USE MODD_BUDGET, ONLY: TBUDGETDATA, NBUDGET_RH, TBUCONF
USE MODI_BUDGET_DDH
USE MODE_FILL_DIMPHYEX, ONLY: FILL_DIMPHYEX

USE MODI_RAIN_ICE

USE MODI_RAIN_ICE_OLD

USE DDH_MIX , ONLY : TYP_DDH
USE YOMLDDH , ONLY : TLDDH
USE YOMMDDH , ONLY : TMDDH

IMPLICIT NONE

INTEGER   :: KPROMA  
INTEGER   :: KKA  
INTEGER   :: KKU  
INTEGER   :: KKL  
INTEGER   :: KLON    
INTEGER   :: KLEV     
INTEGER   :: KFDIA
INTEGER   :: KRR      
INTEGER   :: KTCOUNT  
INTEGER   :: KSPLITR  
INTEGER   :: KEZDIAG  

PARAMETER (KLON=1,KLEV=1,KRR=1)

LOGICAL             :: OSUBG_COND 
CHARACTER (LEN=4)   :: CSUBG_AUCV_RC
CHARACTER (LEN=80)  :: CSUBG_AUCV_RI
LOGICAL             :: OSEDIC 
CHARACTER (LEN=4)   :: CSEDIM  
CHARACTER (LEN=4)   :: CMICRO  
REAL                :: PTSTEP 


REAL, DIMENSION(KLON,1,KLEV)     :: PDZZ     
REAL, DIMENSION(KLON,1,KLEV)     :: PRHODJ  
REAL, DIMENSION(KLON,1,KLEV)     :: PRHODREF
REAL, DIMENSION(KLON,1,KLEV)     :: PEXNREF 
REAL, DIMENSION(KLON,1,KLEV)     :: PPABSM  
REAL, DIMENSION(KLON,1,KLEV)     :: PHLC_HRC
REAL, DIMENSION(KLON,1,KLEV)     :: PHLC_HCF
REAL, DIMENSION(KLON,1,KLEV)     :: PHLI_HRI
REAL, DIMENSION(KLON,1,KLEV)     :: PHLI_HCF
REAL, DIMENSION(KLON,1,KLEV)     :: PTHT    
REAL, DIMENSION(KLON,1,KLEV,KRR) :: PRT   
REAL, DIMENSION(KLON,1,KLEV)     :: PSIGS   
REAL, DIMENSION(KLON,1,KLEV)     :: PCLDFR  
REAL, DIMENSION(KLON,1,KLEV)     :: PTHS    
REAL, DIMENSION(KLON,1,KLEV,KRR) :: PRS   
REAL, DIMENSION(KLON,1,KLEV)     :: PEVAP 
REAL, DIMENSION(KLON,1,KLEV)     :: PCIT  
REAL, DIMENSION(KLON,1)          :: PSEA  
REAL, DIMENSION(KLON,1)          :: PTOWN  
REAL, DIMENSION(KLON,1)          :: PINPRR
REAL, DIMENSION(KLON,1)          :: PINPRS
REAL, DIMENSION(KLON,1)          :: PINPRG
REAL, DIMENSION(KLON,1,KLEV,KRR) :: PFPR 
LOGICAL :: OWARM 
LOGICAL :: OCND2 

INTEGER :: JRR           

REAL, DIMENSION(KLON,1):: ZINDEP     
REAL, DIMENSION(KLON,1,KLEV):: ZRAINFR
REAL, DIMENSION(KLON,1):: ZINPRC    
REAL  :: ZMASSTOT                   
REAL  :: ZMASSPOS                   
REAL  :: ZRATIO                     

LOGICAL, DIMENSION(KLON, 1, KLEV) :: LLMICRO 

TYPE(TBUDGETDATA), DIMENSION(NBUDGET_RH) :: YLBUDGET 
TYPE(DIMPHYEX_t) :: YLDIMPHYEX

INTEGER :: IPROMA, ISIZE
INTEGER :: MYPROC, ITID

CHARACTER(LEN=20) :: CLOFILE
INTEGER           :: IFILE
LOGICAL           :: LFILEEXISTS


CALL FILL_DIMPHYEX(YLDIMPHYEX, KLON, 1, KLEV, 0, KFDIA)

CMICRO='ICE3'
  IFILE=0
  LFILEEXISTS=.TRUE.
  DO WHILE(LFILEEXISTS)
    IFILE=IFILE+1
    WRITE(CLOFILE, '(I4.4,"_",I2.2,"_",I8.8,".dat")') MYPROC, ITID, IFILE
    INQUIRE(FILE=CLOFILE, EXIST=LFILEEXISTS)
  ENDDO
  IF(IFILE==10)THEN
    PRINT*, "OSEDIC, OCND2, CSEDIM", OSEDIC, OCND2, CSEDIM
    PRINT*, "CSUBG_AUCV_RC, CSUBG_AUCV_RI, OWARM", CSUBG_AUCV_RC, CSUBG_AUCV_RI, OWARM
    PRINT*, "PTSTEP, KRR", PTSTEP, KRR
  ENDIF
  LFILEEXISTS=IFILE<500
  IF(LFILEEXISTS) THEN
    IFILE=7+ITID
    OPEN(IFILE, FILE=CLOFILE, FORM='unformatted') !,access='stream')
    WRITE(IFILE) IPROMA, ISIZE
    WRITE(IFILE) SIZE(PRHODJ, 1), SIZE(PRHODJ, 2), SIZE(PRHODJ, 3), SIZE(PRT, 4)
    WRITE(IFILE) LLMICRO
    WRITE(IFILE) PEXNREF
    WRITE(IFILE) PDZZ
    WRITE(IFILE) PRHODJ
    WRITE(IFILE) PRHODREF
    WRITE(IFILE) PEXNREF
    WRITE(IFILE) PPABSM
    WRITE(IFILE) PCIT
    WRITE(IFILE) PCLDFR
    WRITE(IFILE) PHLC_HRC
    WRITE(IFILE) PHLC_HCF
    WRITE(IFILE) PHLI_HRI
    WRITE(IFILE) PHLI_HCF
    WRITE(IFILE) PTHT
    WRITE(IFILE) PRT
    WRITE(IFILE) PTHS
    WRITE(IFILE) PRS
    WRITE(IFILE) PSIGS
    WRITE(IFILE) PSEA
    WRITE(IFILE) PTOWN
  ENDIF

    CALL RAIN_ICE(  YLDIMPHYEX, CST, PARAM_ICE, RAIN_ICE_PARAM, &
                 &  RAIN_ICE_DESCR, TBUCONF, &
                 &  IPROMA, ISIZE, &
                 &  OSEDIC=OSEDIC, OCND2=OCND2, HSEDIM=CSEDIM, &
                 &  HSUBG_AUCV_RC=CSUBG_AUCV_RC, HSUBG_AUCV_RI=CSUBG_AUCV_RI,&
                 &  OWARM=OWARM, &
                 &  PTSTEP=2*PTSTEP, &
                 &  KRR=KRR, ODMICRO=LLMICRO, PEXN=PEXNREF,            &
                 &  PDZZ=PDZZ, PRHODJ=PRHODJ, PRHODREF=PRHODREF,PEXNREF=PEXNREF,&
                 &  PPABST=PPABSM, PCIT=PCIT, PCLDFR=PCLDFR,  &
                 &  PHLC_HRC=PHLC_HRC, PHLC_HCF=PHLC_HCF, &
                 &  PHLI_HRI=PHLI_HRI, PHLI_HCF=PHLI_HCF, &
                 &  PTHT=PTHT,PRVT=PRT(:,:,:,1),PRCT=PRT(:,:,:,2), &
                 &  PRRT=PRT(:,:,:,3), &
                 &  PRIT=PRT(:,:,:,4), PRST=PRT(:,:,:,5), &
                 &  PRGT=PRT(:,:,:,6),       &
                 &  PTHS=PTHS, PRVS=PRS(:,:,:,1),PRCS=PRS(:,:,:,2),&
                 &  PRRS=PRS(:,:,:,3),&
                 &  PRIS=PRS(:,:,:,4),PRSS= PRS(:,:,:,5),PRGS= PRS(:,:,:,6),&
                 &  PINPRC=ZINPRC,PINPRR=PINPRR,PEVAP3D=PEVAP,&
                 &  PINPRS=PINPRS, PINPRG=PINPRG, PINDEP=ZINDEP, PRAINFR=ZRAINFR, &
                 &  PSIGS=PSIGS, &
                 &  TBUDGETS=YLBUDGET, KBUDGETS=SIZE(YLBUDGET), &
                 &  PSEA=PSEA, PTOWN=PTOWN, PFPR=PFPR)
  IF(LFILEEXISTS) THEN
    WRITE(IFILE) PCIT
    WRITE(IFILE) PRS
    WRITE(IFILE) ZINPRC
    WRITE(IFILE) PINPRR
    WRITE(IFILE) PEVAP
    WRITE(IFILE) PINPRS
    WRITE(IFILE) PINPRG
    WRITE(IFILE) ZINDEP
    WRITE(IFILE) ZRAINFR
    WRITE(IFILE) PFPR
  ENDIF



END PROGRAM
